jobs:
- job: 'Linux'
  pool:
    vmImage: ubuntu-16.04
  
  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH

  - script: conda create -n build -qy python=3.7 conda-build anaconda-client
    displayName: Create Conda env

  - script: |
      source activate build
      conda build --output-folder $(Build.ArtifactStagingDirectory) .
    displayName: Build Conda packages

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'conda'

- job: 'Windows'
  pool:
    vmImage: vs2017-win2016

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH
  
  - script: conda create -n build -qy python=3.7 conda-build anaconda-client
    displayName: Create Conda env

  - script: |
      call activate build
      conda build --output-folder $(Build.ArtifactStagingDirectory) .
    displayName: Build Conda packages

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'conda'

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create -n build -qy python=3.7 conda-build anaconda-client
    displayName: Create Conda env

  - script: |
      source activate build
      conda build --output-folder $(Build.ArtifactStagingDirectory) .
    displayName: Build Conda packages
  
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'conda'

- job: 'Publish'
  pool:
    vmImage: ubuntu-16.04
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  dependsOn:
  - Linux
  - Windows
  - macOS
  
  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH

  - script: conda create -n build -qy python=3.7 anaconda-client
    displayName: Create Conda env

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: current
      artifactName: conda
      downloadType: single
      downloadPath: conda-bld
  
  - script: |
      find conda-bld -name '*.tar.bz2'
    displayName: List build artifacts

  - script: |
      source activate build
      ls conda-bld/conda/*/hpfrec-*.tar.bz2
      anaconda --token "$DECODED_CONDA_TOKEN" --verbose upload conda-bld/conda/*/hpfrec-*.tar.bz2
    displayName: Upload Conda packages
    env:
      DECODED_CONDA_TOKEN: $(ANACONDA_TOKEN)