{% set name = "pickle5" %}
{% set version = "0.0.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f8ad2c9f4dc6cb52db232949c26c9cd865a7e624edb270101bede142c332858c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pickle5
    - pickle5.test

about:
  home: "https://github.com/pitrou/pickle5-backport"
  license: Python Software Foundation
  license_family: OTHER
  license_file: 
  summary: "Backport of the pickle 5 protocol (PEP 574) and other pickle changes"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - mdekstrand
