{% set name = "hpfrec" %}
{% set version = "0.2.2.15" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4293cb99cac067617eaa646cf8d45eaac27f495fa7c069d7a415cc21bcb834b4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - {{ compiler('c') }} #[not win]
    - llvm-openmp #[osx]
  host:
    - cython
    - numpy
    - pandas >=0.21
    - pip
    - python
    - scipy
    - llvm-openmp #[osx]
  run:
    - numpy
    - pandas >=0.21
    - python
    - scipy
    - llvm-openmp #[osx]

test:
  imports:
    - hpfrec

about:
  home: https://github.com/david-cortes/hpfrec
  license: BSD2
  license_family: BSD
  license_file: 
  summary: Hierarchical Poisson matrix factorization for recommender systems
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - mdekstrand
