{% set name = "hpfrec" %}
{% set version = "0.2.2.22" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd9fb9be11c762bc8da0a9640ae55a238c4f94e7d79f15ea3f8bad16bcee10c7

build:
  number: 0
  # script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script: {{ PYTHON }} setup.py install

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp #[osx]
  host:
    - cython
    - numpy
    - pandas >=0.21
    - pip
    - python
    - scipy
    - llvm-openmp #[osx]
  run:
    - numpy
    - pandas >=0.21
    - python
    - scipy
    - llvm-openmp #[osx]

test:
  imports:
    - hpfrec

about:
  home: https://github.com/david-cortes/hpfrec
  license: BSD2
  license_family: BSD
  license_file: 
  summary: Hierarchical Poisson matrix factorization for recommender systems
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - mdekstrand
